version: '3.9'

services:
  mongodb:
    image: mongo:focal
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db:/data/db
  postgres-db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=petowner
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgres/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/1-postgres-init.sql