micronaut:
  application:
    name: petOwner
  server:
    port: 8080
  security:
    enabled: true
    authentication: session
    session:
      enabled: true
  endpoints:
    login:
      enabled: true
    logout:
      enabled: true


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/petowner
    driverClassName: org.postgresql.Driver
    username: 'petowner'
    password: 'petowner'
    dialect: POSTGRES


netty:
  default:
    allocator:
      max-order: 3



identity-store:
  users:
    alice: alice@1
    bob: bob@2
    charlie: charlie@3
  roles:
    alice: ADMIN
    bob: VIEW
    charlie: VIEW

jpa.default.properties.hibernate.hbm2ddl.auto: update
