micronaut:
  application:
    name: clinicReviews
  server:
    port: 8082
#  ssl:
#    enabled: true
#    key-store:
#      path:
#        file: /certificate/cert.p12
#      type: PKCS12
#      password: ${CERT_PASS}
#  security:
#    authentication: idtoken
#    oauth2:
#      clients:
#        okta:
#          client-secret: MvSU1cx05pqoUIQSZfLJupUGbYMS3GL5eLGLdjrj
#          client-id: 0oa4nw563lx9sv8Tm5d7
#          openid:
#            issuer: https://dev-29926649.okta.com/oauth2/default
#    endpoints:
#      logout:
#        get-allowed: true

kafka:
  bootstrap:
    servers: localhost:9092

netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://vetReview:vetReview@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/vet-review
